### ISSUE TITLE
Listen mode does not respect the -p argument

### ISSUE THREAD

**Issue by bepursuant** [TrshPuppy/NetPuppy#10]
When attempting listen mode, the -p parameter is required but not respected. No matter what -p argument is passed, we are listening on port 44440.

**Comment by TrshPuppy** [comment]
Thank you! Fixed this today (see branch `2-netpuppy-connect`. This was due to a hard-coded port value. Will be merged to main soon!

**Comment by bepursuant** [comment]
ah sorry, I didn't see the branches! The argparse impl here re #11 is probably worth a look though
