### ISSUE TITLE
issue with connection

### ISSUE THREAD

**Issue by pianoplayerjames** [TrshPuppy/netpuppy#52]
If I set up an offense-peer and a connect-back connects to it, the session is fine but as soon as the connect-back closes the connection, the offense-peer seems to cut out. There should be a way for the offense-peer to stay alive when connect-back peers disconnect or even allow for offense-peers to allow channels so you can have multiple connect-back sessions

**Comment by TrshPuppy** [comment]
Right now, the offense peer does not handle more than one connection. Additionally, the connection, whether made by a listener or client process, is treated as the same in the code once it's made.

The two peer types would have to be de-coupled a bit more which is the direction NP is heading towards anyway. For now, keeping the listener/ offense peer to one connection is fine.  Plan to change this when the offense peer is re-factored to handle multiple clients.
